name: Ensure Project Structure

# Wyzwala się ręcznie (Workflow Dispatch) i przy każdym pushu poza zmianami w .github/
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'

jobs:
  ensure-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ensure docs/index.html exists
        run: |
          mkdir -p docs
          if [ ! -f docs/index.html ]; then
            cat << 'EOF' > docs/index.html
<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Kalkulator</title>
</head>
<body>
  <h1>Kalkulator</h1>
  <script src="app.js"></script>
</body>
</html>
EOF
          fi

      - name: Ensure docs/app.js exists
        run: |
          if [ ! -f docs/app.js ]; then
            echo 'console.log("Kalkulator dziala");' > docs/app.js
          fi

      - name: Ensure netlify/functions skeleton
        run: |
          mkdir -p netlify/functions
          for f in start-session close-session hotpay-webhook; do
            file="netlify/functions/$f.js"
            if [ ! -f "$file" ]; then
              cat << EOF > "$file"
// $f skeleton
exports.handler = async function(event) {
  return { statusCode: 200, body: JSON.stringify({ message: "$f OK" }) };
};
EOF
            fi
          done

      - name: Ensure README.md exists
        run: |
          if [ ! -f README.md ]; then
            echo '# Kalkulator with Serverless Functions' > README.md
          fi

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs netlify README.md
          git diff --quiet && echo "No changes to commit" || git commit -m "🛠️ Ensure project structure"
          git push
